version: "1"
services:
  backend:
    build: ./backend
    container_name: node-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
